name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_systems: [ubuntu-latest, macos-latest]
        excluding:
          - nodejs_version: 18
            operating_systems: macos-latest
    runs-on: ${{ matrix.operating_systems }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.operating_systems }}

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test

      - name: Find test result
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
          echo "XML files:"
          find . -name "*.xml" -type f

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: mocha-test-results
          path: test-results.xml
          #if-no-files-found: error
      